server:
  port: 8004

spring:
  application:
    name: zhiyou-spring-boot
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  data:
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Shanghai

app:
  data-path: /app/data/

logging:
  level:
    com.zhiyou: debug
